/*
	Generated by KBEngine!
	Please do not modify this file!
	
	tools = kbcmd
*/

import { EntityCall,DataTypes,KBETypes } from './KBEngine';
import EntityDef from './EntityDef';
// defined in */scripts/entity_defs/Test.def
export class EntityBaseEntityCall_TestBase extends EntityCall {
	public entityComponentPropertyID:number = 0;

	constructor(ecpID: number, eid: number) { 
		super(eid, "Test");
		this.entityComponentPropertyID = ecpID;
		this.entityCallType = 1;
	}

	public say(arg1:number){
		let pBundle = this.NewCallToMethod("say", this.entityComponentPropertyID);
		if(pBundle == null)
			return;

		this.bundle!.WriteInt32(arg1);
		this.SendCall();
	}

}

export class EntityCellEntityCall_TestBase extends EntityCall{
	public entityComponentPropertyID:number = 0;

	constructor(ecpID: number, eid: number) { 
		super(eid, "EntityCellEntityCall_TestBase");
		this.entityComponentPropertyID = ecpID;
		this.className = "Test";
		this.entityCallType = 0;
	}

	public hello(arg1:number){
		let pBundle = this.NewCallToMethod("hello", this.entityComponentPropertyID);
		if(pBundle == null)
			return;

		this.bundle!.WriteInt32(arg1);
		this.SendCall();
	}

}
