/*
	Generated by KBEngine!
	Please do not modify this file!
	
	tools = kbcmd
*/

import { EntityCall,DataTypes,KBETypes } from './KBEngine';
import EntityDef from './EntityDef';
// defined in */scripts/entity_defs/SpaceDuplicate.def
export class EntityBaseEntityCall_SpaceDuplicateBase extends EntityCall {

	constructor(eid: number, ename: string) {
		super(eid, ename);
		this.entityCallType = 1;
	}

}

export class EntityCellEntityCall_SpaceDuplicateBase extends EntityCall{

	constructor(eid: number, ename: string) { 
		super(eid, ename);
		this.entityCallType = 0;
	}

}
