/*
	Generated by KBEngine!
	Please do not modify this file!
	
	tools = kbcmd
*/

import { EntityCall,DataTypes,KBETypes } from './KBEngine';
import EntityDef from './EntityDef';
// defined in */scripts/entity_defs/TestNoBase.def
export class EntityBaseEntityCall_TestNoBaseBase extends EntityCall {
	public entityComponentPropertyID:number = 0;

	constructor(ecpID: number, eid: number) { 
		super(eid, "TestNoBase");
		this.entityComponentPropertyID = ecpID;
		this.entityCallType = 1;
	}

}

export class EntityCellEntityCall_TestNoBaseBase extends EntityCall{
	public entityComponentPropertyID:number = 0;

	constructor(ecpID: number, eid: number) { 
		super(eid, "EntityCellEntityCall_TestNoBaseBase");
		this.entityComponentPropertyID = ecpID;
		this.className = "TestNoBase";
		this.entityCallType = 0;
	}

	public hello(arg1:number){
		let pBundle = this.NewCallToMethod("hello", this.entityComponentPropertyID);
		if(pBundle == null)
			return;

		this.bundle!.WriteInt32(arg1);
		this.SendCall();
	}

}
