/*
	Generated by KBEngine!
	Please do not modify this file!
	
	tools = kbcmd
*/

import { EntityCall,DataTypes,KBETypes } from './KBEngine';
import EntityDef from './EntityDef';
// defined in */scripts/entity_defs/Account.def
export class EntityBaseEntityCall_AccountBase extends EntityCall {

	constructor(eid: number, ename: string) {
		super(eid, ename);
		this.entityCallType = 1;
	}

	public reqAvatarList(){
		let pBundle = this.NewCallToMethod("reqAvatarList", 0);
		if(pBundle == null)
			return;

		this.SendCall();
	}

	public reqCreateAvatar(arg1:number, arg2:string){
		let pBundle = this.NewCallToMethod("reqCreateAvatar", 0);
		if(pBundle == null)
			return;

		this.bundle!.WriteUint8(arg1);
		this.bundle!.WriteUnicode(arg2);
		this.SendCall();
	}

	public reqRemoveAvatar(arg1:string){
		let pBundle = this.NewCallToMethod("reqRemoveAvatar", 0);
		if(pBundle == null)
			return;

		this.bundle!.WriteUnicode(arg1);
		this.SendCall();
	}

	public reqRemoveAvatarDBID(arg1:bigint){
		let pBundle = this.NewCallToMethod("reqRemoveAvatarDBID", 0);
		if(pBundle == null)
			return;

		this.bundle!.WriteUint64(DataTypes.KB_UINT64.fromBigInt(arg1));
		this.SendCall();
	}

	public selectAvatarGame(arg1:bigint){
		let pBundle = this.NewCallToMethod("selectAvatarGame", 0);
		if(pBundle == null)
			return;

		this.bundle!.WriteUint64(DataTypes.KB_UINT64.fromBigInt(arg1));
		this.SendCall();
	}

}

export class EntityCellEntityCall_AccountBase extends EntityCall{

	constructor(eid: number, ename: string) { 
		super(eid, ename);
		this.entityCallType = 0;
	}

}
