/*
	Generated by KBEngine!
	Please do not modify this file!
	tools = kbcmd
*/


import { KBEngineApp ,MemoryStream , DataTypes } from "./KBEngine";


export class Message {
    public id: number = 0;
    public name: string;
    public msglen: number = -1;
    public argtypes: number[] = [];
    public argsType: number = 0;

    constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        this.id = msgid;
        this.name = msgname;
        this.msglen = length;
        this.argsType = argstype;

        this.argtypes = msgargtypes;
        // Dbg.DEBUG_MSG(string.Format("Message::Message() : ({ 0 } / {1} / {2})!", 
        //		msgname, msgid, msglen));
    }

    public handleMessage(msgstream: MemoryStream) {
    }
}

export class Message_Client_onReloginBaseappFailed extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
		let arg1 = msgstream.ReadUint16();
		KBEngineApp.app!.Client_onReloginBaseappFailed(arg1);
	}
}


export class Message_Client_onEntityLeaveWorldOptimized extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
		KBEngineApp.app!.Client_onEntityLeaveWorldOptimized(msgstream); 
	}
}


export class Message_Client_onRemoteMethodCallOptimized extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
		KBEngineApp.app!.Client_onRemoteMethodCallOptimized(msgstream); 
	}
}


export class Message_Client_onUpdatePropertysOptimized extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
		KBEngineApp.app!.Client_onUpdatePropertysOptimized(msgstream); 
	}
}


export class Message_Client_onSetEntityPosAndDir extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
		KBEngineApp.app!.Client_onSetEntityPosAndDir(msgstream); 
	}
}


export class Message_Client_onUpdateBasePos extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
		let arg1 = msgstream.ReadFloat();
		let arg2 = msgstream.ReadFloat();
		let arg3 = msgstream.ReadFloat();
		KBEngineApp.app!.Client_onUpdateBasePos(arg1, arg2, arg3);
	}
}


export class Message_Client_onUpdateBaseDir extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
		KBEngineApp.app!.Client_onUpdateBaseDir(msgstream); 
	}
}


export class Message_Client_onUpdateBasePosXZ extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
		let arg1 = msgstream.ReadFloat();
		let arg2 = msgstream.ReadFloat();
		KBEngineApp.app!.Client_onUpdateBasePosXZ(arg1, arg2);
	}
}


export class Message_Client_onUpdateData extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
		KBEngineApp.app!.Client_onUpdateData(msgstream); 
	}
}


export class Message_Client_onUpdateData_ypr extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
		KBEngineApp.app!.Client_onUpdateData_ypr(msgstream); 
	}
}


export class Message_Client_onUpdateData_yp extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
		KBEngineApp.app!.Client_onUpdateData_yp(msgstream); 
	}
}


export class Message_Client_onUpdateData_yr extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
		KBEngineApp.app!.Client_onUpdateData_yr(msgstream); 
	}
}


export class Message_Client_onUpdateData_pr extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
		KBEngineApp.app!.Client_onUpdateData_pr(msgstream); 
	}
}


export class Message_Client_onUpdateData_y extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
		KBEngineApp.app!.Client_onUpdateData_y(msgstream); 
	}
}


export class Message_Client_onUpdateData_p extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
		KBEngineApp.app!.Client_onUpdateData_p(msgstream); 
	}
}


export class Message_Client_onUpdateData_r extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
		KBEngineApp.app!.Client_onUpdateData_r(msgstream); 
	}
}


export class Message_Client_onUpdateData_xz extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
		KBEngineApp.app!.Client_onUpdateData_xz(msgstream); 
	}
}


export class Message_Client_onUpdateData_xz_ypr extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
		KBEngineApp.app!.Client_onUpdateData_xz_ypr(msgstream); 
	}
}


export class Message_Client_onUpdateData_xz_yp extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
		KBEngineApp.app!.Client_onUpdateData_xz_yp(msgstream); 
	}
}


export class Message_Client_onUpdateData_xz_yr extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
		KBEngineApp.app!.Client_onUpdateData_xz_yr(msgstream); 
	}
}


export class Message_Client_onUpdateData_xz_pr extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
		KBEngineApp.app!.Client_onUpdateData_xz_pr(msgstream); 
	}
}


export class Message_Client_onUpdateData_xz_y extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
		KBEngineApp.app!.Client_onUpdateData_xz_y(msgstream); 
	}
}


export class Message_Client_onUpdateData_xz_p extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
		KBEngineApp.app!.Client_onUpdateData_xz_p(msgstream); 
	}
}


export class Message_Client_onUpdateData_xz_r extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
		KBEngineApp.app!.Client_onUpdateData_xz_r(msgstream); 
	}
}


export class Message_Client_onUpdateData_xyz extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
		KBEngineApp.app!.Client_onUpdateData_xyz(msgstream); 
	}
}


export class Message_Client_onUpdateData_xyz_ypr extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
		KBEngineApp.app!.Client_onUpdateData_xyz_ypr(msgstream); 
	}
}


export class Message_Client_onUpdateData_xyz_yp extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
		KBEngineApp.app!.Client_onUpdateData_xyz_yp(msgstream); 
	}
}


export class Message_Client_onUpdateData_xyz_yr extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
		KBEngineApp.app!.Client_onUpdateData_xyz_yr(msgstream); 
	}
}


export class Message_Client_onUpdateData_xyz_pr extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
		KBEngineApp.app!.Client_onUpdateData_xyz_pr(msgstream); 
	}
}


export class Message_Client_onUpdateData_xyz_y extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
		KBEngineApp.app!.Client_onUpdateData_xyz_y(msgstream); 
	}
}


export class Message_Client_onUpdateData_xyz_p extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
		KBEngineApp.app!.Client_onUpdateData_xyz_p(msgstream); 
	}
}


export class Message_Client_onUpdateData_xyz_r extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
		KBEngineApp.app!.Client_onUpdateData_xyz_r(msgstream); 
	}
}


export class Message_Client_onUpdateData_ypr_optimized extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
		KBEngineApp.app!.Client_onUpdateData_ypr_optimized(msgstream); 
	}
}


export class Message_Client_onUpdateData_yp_optimized extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
		KBEngineApp.app!.Client_onUpdateData_yp_optimized(msgstream); 
	}
}


export class Message_Client_onUpdateData_yr_optimized extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
		KBEngineApp.app!.Client_onUpdateData_yr_optimized(msgstream); 
	}
}


export class Message_Client_onUpdateData_pr_optimized extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
		KBEngineApp.app!.Client_onUpdateData_pr_optimized(msgstream); 
	}
}


export class Message_Client_onUpdateData_y_optimized extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
		KBEngineApp.app!.Client_onUpdateData_y_optimized(msgstream); 
	}
}


export class Message_Client_onUpdateData_p_optimized extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
		KBEngineApp.app!.Client_onUpdateData_p_optimized(msgstream); 
	}
}


export class Message_Client_onUpdateData_r_optimized extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
		KBEngineApp.app!.Client_onUpdateData_r_optimized(msgstream); 
	}
}


export class Message_Client_onUpdateData_xz_optimized extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
		KBEngineApp.app!.Client_onUpdateData_xz_optimized(msgstream); 
	}
}


export class Message_Client_onUpdateData_xz_ypr_optimized extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
		KBEngineApp.app!.Client_onUpdateData_xz_ypr_optimized(msgstream); 
	}
}


export class Message_Client_onUpdateData_xz_yp_optimized extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
		KBEngineApp.app!.Client_onUpdateData_xz_yp_optimized(msgstream); 
	}
}


export class Message_Client_onUpdateData_xz_yr_optimized extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
		KBEngineApp.app!.Client_onUpdateData_xz_yr_optimized(msgstream); 
	}
}


export class Message_Client_onUpdateData_xz_pr_optimized extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
		KBEngineApp.app!.Client_onUpdateData_xz_pr_optimized(msgstream); 
	}
}


export class Message_Client_onUpdateData_xz_y_optimized extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
		KBEngineApp.app!.Client_onUpdateData_xz_y_optimized(msgstream); 
	}
}


export class Message_Client_onUpdateData_xz_p_optimized extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
		KBEngineApp.app!.Client_onUpdateData_xz_p_optimized(msgstream); 
	}
}


export class Message_Client_onUpdateData_xz_r_optimized extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
		KBEngineApp.app!.Client_onUpdateData_xz_r_optimized(msgstream); 
	}
}


export class Message_Client_onUpdateData_xyz_optimized extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
		KBEngineApp.app!.Client_onUpdateData_xyz_optimized(msgstream); 
	}
}


export class Message_Client_onUpdateData_xyz_ypr_optimized extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
		KBEngineApp.app!.Client_onUpdateData_xyz_ypr_optimized(msgstream); 
	}
}


export class Message_Client_onUpdateData_xyz_yp_optimized extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
		KBEngineApp.app!.Client_onUpdateData_xyz_yp_optimized(msgstream); 
	}
}


export class Message_Client_onUpdateData_xyz_yr_optimized extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
		KBEngineApp.app!.Client_onUpdateData_xyz_yr_optimized(msgstream); 
	}
}


export class Message_Client_onUpdateData_xyz_pr_optimized extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
		KBEngineApp.app!.Client_onUpdateData_xyz_pr_optimized(msgstream); 
	}
}


export class Message_Client_onUpdateData_xyz_y_optimized extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
		KBEngineApp.app!.Client_onUpdateData_xyz_y_optimized(msgstream); 
	}
}


export class Message_Client_onUpdateData_xyz_p_optimized extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
		KBEngineApp.app!.Client_onUpdateData_xyz_p_optimized(msgstream); 
	}
}


export class Message_Client_onUpdateData_xyz_r_optimized extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
		KBEngineApp.app!.Client_onUpdateData_xyz_r_optimized(msgstream); 
	}
}


export class Message_Client_onImportServerErrorsDescr extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
		KBEngineApp.app!.Client_onImportServerErrorsDescr(msgstream); 
	}
}


export class Message_Client_onImportClientSDK extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
		KBEngineApp.app!.Client_onImportClientSDK(msgstream); 
	}
}


export class Message_Client_initSpaceData extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
		KBEngineApp.app!.Client_initSpaceData(msgstream); 
	}
}


export class Message_Client_setSpaceData extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
		let arg1 = msgstream.ReadUint32();
		let arg2 = msgstream.ReadString();
		let arg3 = msgstream.ReadString();
		KBEngineApp.app!.Client_setSpaceData(arg1, arg2, arg3);
	}
}


export class Message_Client_delSpaceData extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
		let arg1 = msgstream.ReadUint32();
		let arg2 = msgstream.ReadString();
		KBEngineApp.app!.Client_delSpaceData(arg1, arg2);
	}
}


export class Message_Client_onReqAccountResetPasswordCB extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
		let arg1 = msgstream.ReadUint16();
		KBEngineApp.app!.Client_onReqAccountResetPasswordCB(arg1);
	}
}


export class Message_Client_onReqAccountBindEmailCB extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
		let arg1 = msgstream.ReadUint16();
		KBEngineApp.app!.Client_onReqAccountBindEmailCB(arg1);
	}
}


export class Message_Client_onReqAccountNewPasswordCB extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
		let arg1 = msgstream.ReadUint16();
		KBEngineApp.app!.Client_onReqAccountNewPasswordCB(arg1);
	}
}


export class Message_Client_onReloginBaseappSuccessfully extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
		KBEngineApp.app!.Client_onReloginBaseappSuccessfully(msgstream); 
	}
}


export class Message_Client_onAppActiveTickCB extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
		KBEngineApp.app!.Client_onAppActiveTickCB(); 
	}
}


export class Message_Client_onCreateAccountResult extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
		KBEngineApp.app!.Client_onCreateAccountResult(msgstream); 
	}
}


export class Message_Client_onLoginSuccessfully extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
		KBEngineApp.app!.Client_onLoginSuccessfully(msgstream); 
	}
}


export class Message_Client_onLoginFailed extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
		KBEngineApp.app!.Client_onLoginFailed(msgstream); 
	}
}


export class Message_Client_onCreatedProxies extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
		let arg1 = msgstream.ReadUint64();
		let arg2 = msgstream.ReadInt32();
		let arg3 = msgstream.ReadString();
		KBEngineApp.app!.Client_onCreatedProxies(arg1, arg2, arg3);
	}
}


export class Message_Client_onLoginBaseappFailed extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
		let arg1 = msgstream.ReadUint16();
		KBEngineApp.app!.Client_onLoginBaseappFailed(arg1);
	}
}


export class Message_Client_onRemoteMethodCall extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
		KBEngineApp.app!.Client_onRemoteMethodCall(msgstream); 
	}
}


export class Message_Client_onEntityEnterWorld extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
		KBEngineApp.app!.Client_onEntityEnterWorld(msgstream); 
	}
}


export class Message_Client_onEntityLeaveWorld extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
		let arg1 = msgstream.ReadInt32();
		KBEngineApp.app!.Client_onEntityLeaveWorld(arg1);
	}
}


export class Message_Client_onEntityEnterSpace extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
		KBEngineApp.app!.Client_onEntityEnterSpace(msgstream); 
	}
}


export class Message_Client_onEntityLeaveSpace extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
		let arg1 = msgstream.ReadInt32();
		KBEngineApp.app!.Client_onEntityLeaveSpace(arg1);
	}
}


export class Message_Client_onUpdatePropertys extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
		KBEngineApp.app!.Client_onUpdatePropertys(msgstream); 
	}
}


export class Message_Client_onEntityDestroyed extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
		let arg1 = msgstream.ReadInt32();
		KBEngineApp.app!.Client_onEntityDestroyed(arg1);
	}
}


export class Message_Client_onStreamDataStarted extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
		let arg1 = msgstream.ReadInt16();
		let arg2 = msgstream.ReadUint32();
		let arg3 = msgstream.ReadString();
		KBEngineApp.app!.Client_onStreamDataStarted(arg1, arg2, arg3);
	}
}


export class Message_Client_onStreamDataRecv extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
		KBEngineApp.app!.Client_onStreamDataRecv(msgstream); 
	}
}


export class Message_Client_onStreamDataCompleted extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
		let arg1 = msgstream.ReadInt16();
		KBEngineApp.app!.Client_onStreamDataCompleted(arg1);
	}
}


export class Message_Client_onKicked extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
		let arg1 = msgstream.ReadUint16();
		KBEngineApp.app!.Client_onKicked(arg1);
	}
}


export class Message_Client_onImportClientMessages extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
		KBEngineApp.app!.Client_onImportClientMessages(msgstream); 
	}
}


export class Message_Client_onImportClientEntityDef extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
		KBEngineApp.app!.Client_onImportClientEntityDef(msgstream); 
	}
}


export class Message_Client_onHelloCB extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
		KBEngineApp.app!.Client_onHelloCB(msgstream); 
	}
}


export class Message_Client_onScriptVersionNotMatch extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
		KBEngineApp.app!.Client_onScriptVersionNotMatch(msgstream); 
	}
}


export class Message_Client_onVersionNotMatch extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
		KBEngineApp.app!.Client_onVersionNotMatch(msgstream); 
	}
}


export class Message_Client_onControlEntity extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
		let arg1 = msgstream.ReadInt32();
		let arg2 = msgstream.ReadInt8();
		KBEngineApp.app!.Client_onControlEntity(arg1, arg2);
	}
}


export class Message_Loginapp_reqCreateAccount extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
	}
}


export class Message_Loginapp_login extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
	}
}


export class Message_Loginapp_hello extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
	}
}


export class Message_Loginapp_importClientMessages extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
	}
}


export class Message_Loginapp_reqCreateMailAccount extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
	}
}


export class Message_Loginapp_importClientSDK extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
	}
}


export class Message_Loginapp_importServerErrorsDescr extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
	}
}


export class Message_Loginapp_onClientActiveTick extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
	}
}


export class Message_Loginapp_reqAccountResetPassword extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
	}
}


export class Message_Baseapp_logoutBaseapp extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
	}
}


export class Message_Baseapp_onUpdateDataFromClient extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
	}
}


export class Message_Baseapp_onUpdateDataFromClientForControlledEntity extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
	}
}


export class Message_Baseapp_reqAccountBindEmail extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
	}
}


export class Message_Baseapp_reqAccountNewPassword extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
	}
}


export class Message_Entity_forwardEntityMessageToCellappFromClient extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
	}
}


export class Message_Baseapp_hello extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
	}
}


export class Message_Baseapp_loginBaseapp extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
	}
}


export class Message_Baseapp_reloginBaseapp extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
	}
}


export class Message_Baseapp_onRemoteCallCellMethodFromClient extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
	}
}


export class Message_Baseapp_onClientActiveTick extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
	}
}


export class Message_Baseapp_importClientMessages extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
	}
}


export class Message_Baseapp_importClientEntityDef extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
	}
}


export class Message_Entity_onRemoteMethodCall extends Message {

	constructor(msgid: number, msgname: string, length: number, argstype: number, msgargtypes: number[]) {
        super(msgid, msgname, length, argstype, msgargtypes);
    }

	public override handleMessage(msgstream: MemoryStream) {
	}
}


export default class Messages {

    public static loginappMessages: { [key: string]: Message } = {};
    public static baseappMessages: { [key: string]: Message } = {};
    public static clientMessages: { [key: string]: Message } = {};
    public static messages: { [key: string]: Message } = {};

	static clear() {
        Messages.loginappMessages = {};
        Messages.baseappMessages = {};
        Messages.clientMessages = {};
        Messages.messages = {};

        Messages.BindFixedMessage();
    }

    static BindFixedMessage() {

		let Client_onReloginBaseappFailed_argstypes: number[] = [];
		Client_onReloginBaseappFailed_argstypes.push(3);
		Messages.messages["Client_onReloginBaseappFailed"] = new Message_Client_onReloginBaseappFailed(8, "Client_onReloginBaseappFailed", 2, 0, Client_onReloginBaseappFailed_argstypes);
		Messages.clientMessages[8] = Messages.messages["Client_onReloginBaseappFailed"];

		Messages.messages["Client_onEntityLeaveWorldOptimized"] = new Message_Client_onEntityLeaveWorldOptimized(9, "Client_onEntityLeaveWorldOptimized", -1, -1, []); 
		Messages.clientMessages[9] = Messages.messages["Client_onEntityLeaveWorldOptimized"];

		Messages.messages["Client_onRemoteMethodCallOptimized"] = new Message_Client_onRemoteMethodCallOptimized(10, "Client_onRemoteMethodCallOptimized", -1, -1, []); 
		Messages.clientMessages[10] = Messages.messages["Client_onRemoteMethodCallOptimized"];

		Messages.messages["Client_onUpdatePropertysOptimized"] = new Message_Client_onUpdatePropertysOptimized(11, "Client_onUpdatePropertysOptimized", -1, -1, []); 
		Messages.clientMessages[11] = Messages.messages["Client_onUpdatePropertysOptimized"];

		Messages.messages["Client_onSetEntityPosAndDir"] = new Message_Client_onSetEntityPosAndDir(12, "Client_onSetEntityPosAndDir", -1, -1, []); 
		Messages.clientMessages[12] = Messages.messages["Client_onSetEntityPosAndDir"];


		let Client_onUpdateBasePos_argstypes: number[] = [];
		Client_onUpdateBasePos_argstypes.push(13);
		Client_onUpdateBasePos_argstypes.push(13);
		Client_onUpdateBasePos_argstypes.push(13);
		Messages.messages["Client_onUpdateBasePos"] = new Message_Client_onUpdateBasePos(13, "Client_onUpdateBasePos", 12, 0, Client_onUpdateBasePos_argstypes);
		Messages.clientMessages[13] = Messages.messages["Client_onUpdateBasePos"];

		Messages.messages["Client_onUpdateBaseDir"] = new Message_Client_onUpdateBaseDir(14, "Client_onUpdateBaseDir", -1, -1, []); 
		Messages.clientMessages[14] = Messages.messages["Client_onUpdateBaseDir"];


		let Client_onUpdateBasePosXZ_argstypes: number[] = [];
		Client_onUpdateBasePosXZ_argstypes.push(13);
		Client_onUpdateBasePosXZ_argstypes.push(13);
		Messages.messages["Client_onUpdateBasePosXZ"] = new Message_Client_onUpdateBasePosXZ(15, "Client_onUpdateBasePosXZ", 8, 0, Client_onUpdateBasePosXZ_argstypes);
		Messages.clientMessages[15] = Messages.messages["Client_onUpdateBasePosXZ"];

		Messages.messages["Client_onUpdateData"] = new Message_Client_onUpdateData(16, "Client_onUpdateData", -1, -1, []); 
		Messages.clientMessages[16] = Messages.messages["Client_onUpdateData"];

		Messages.messages["Client_onUpdateData_ypr"] = new Message_Client_onUpdateData_ypr(17, "Client_onUpdateData_ypr", -1, -1, []); 
		Messages.clientMessages[17] = Messages.messages["Client_onUpdateData_ypr"];

		Messages.messages["Client_onUpdateData_yp"] = new Message_Client_onUpdateData_yp(18, "Client_onUpdateData_yp", -1, -1, []); 
		Messages.clientMessages[18] = Messages.messages["Client_onUpdateData_yp"];

		Messages.messages["Client_onUpdateData_yr"] = new Message_Client_onUpdateData_yr(19, "Client_onUpdateData_yr", -1, -1, []); 
		Messages.clientMessages[19] = Messages.messages["Client_onUpdateData_yr"];

		Messages.messages["Client_onUpdateData_pr"] = new Message_Client_onUpdateData_pr(20, "Client_onUpdateData_pr", -1, -1, []); 
		Messages.clientMessages[20] = Messages.messages["Client_onUpdateData_pr"];

		Messages.messages["Client_onUpdateData_y"] = new Message_Client_onUpdateData_y(21, "Client_onUpdateData_y", -1, -1, []); 
		Messages.clientMessages[21] = Messages.messages["Client_onUpdateData_y"];

		Messages.messages["Client_onUpdateData_p"] = new Message_Client_onUpdateData_p(22, "Client_onUpdateData_p", -1, -1, []); 
		Messages.clientMessages[22] = Messages.messages["Client_onUpdateData_p"];

		Messages.messages["Client_onUpdateData_r"] = new Message_Client_onUpdateData_r(23, "Client_onUpdateData_r", -1, -1, []); 
		Messages.clientMessages[23] = Messages.messages["Client_onUpdateData_r"];

		Messages.messages["Client_onUpdateData_xz"] = new Message_Client_onUpdateData_xz(24, "Client_onUpdateData_xz", -1, -1, []); 
		Messages.clientMessages[24] = Messages.messages["Client_onUpdateData_xz"];

		Messages.messages["Client_onUpdateData_xz_ypr"] = new Message_Client_onUpdateData_xz_ypr(25, "Client_onUpdateData_xz_ypr", -1, -1, []); 
		Messages.clientMessages[25] = Messages.messages["Client_onUpdateData_xz_ypr"];

		Messages.messages["Client_onUpdateData_xz_yp"] = new Message_Client_onUpdateData_xz_yp(26, "Client_onUpdateData_xz_yp", -1, -1, []); 
		Messages.clientMessages[26] = Messages.messages["Client_onUpdateData_xz_yp"];

		Messages.messages["Client_onUpdateData_xz_yr"] = new Message_Client_onUpdateData_xz_yr(27, "Client_onUpdateData_xz_yr", -1, -1, []); 
		Messages.clientMessages[27] = Messages.messages["Client_onUpdateData_xz_yr"];

		Messages.messages["Client_onUpdateData_xz_pr"] = new Message_Client_onUpdateData_xz_pr(28, "Client_onUpdateData_xz_pr", -1, -1, []); 
		Messages.clientMessages[28] = Messages.messages["Client_onUpdateData_xz_pr"];

		Messages.messages["Client_onUpdateData_xz_y"] = new Message_Client_onUpdateData_xz_y(29, "Client_onUpdateData_xz_y", -1, -1, []); 
		Messages.clientMessages[29] = Messages.messages["Client_onUpdateData_xz_y"];

		Messages.messages["Client_onUpdateData_xz_p"] = new Message_Client_onUpdateData_xz_p(30, "Client_onUpdateData_xz_p", -1, -1, []); 
		Messages.clientMessages[30] = Messages.messages["Client_onUpdateData_xz_p"];

		Messages.messages["Client_onUpdateData_xz_r"] = new Message_Client_onUpdateData_xz_r(31, "Client_onUpdateData_xz_r", -1, -1, []); 
		Messages.clientMessages[31] = Messages.messages["Client_onUpdateData_xz_r"];

		Messages.messages["Client_onUpdateData_xyz"] = new Message_Client_onUpdateData_xyz(32, "Client_onUpdateData_xyz", -1, -1, []); 
		Messages.clientMessages[32] = Messages.messages["Client_onUpdateData_xyz"];

		Messages.messages["Client_onUpdateData_xyz_ypr"] = new Message_Client_onUpdateData_xyz_ypr(33, "Client_onUpdateData_xyz_ypr", -1, -1, []); 
		Messages.clientMessages[33] = Messages.messages["Client_onUpdateData_xyz_ypr"];

		Messages.messages["Client_onUpdateData_xyz_yp"] = new Message_Client_onUpdateData_xyz_yp(34, "Client_onUpdateData_xyz_yp", -1, -1, []); 
		Messages.clientMessages[34] = Messages.messages["Client_onUpdateData_xyz_yp"];

		Messages.messages["Client_onUpdateData_xyz_yr"] = new Message_Client_onUpdateData_xyz_yr(35, "Client_onUpdateData_xyz_yr", -1, -1, []); 
		Messages.clientMessages[35] = Messages.messages["Client_onUpdateData_xyz_yr"];

		Messages.messages["Client_onUpdateData_xyz_pr"] = new Message_Client_onUpdateData_xyz_pr(36, "Client_onUpdateData_xyz_pr", -1, -1, []); 
		Messages.clientMessages[36] = Messages.messages["Client_onUpdateData_xyz_pr"];

		Messages.messages["Client_onUpdateData_xyz_y"] = new Message_Client_onUpdateData_xyz_y(37, "Client_onUpdateData_xyz_y", -1, -1, []); 
		Messages.clientMessages[37] = Messages.messages["Client_onUpdateData_xyz_y"];

		Messages.messages["Client_onUpdateData_xyz_p"] = new Message_Client_onUpdateData_xyz_p(38, "Client_onUpdateData_xyz_p", -1, -1, []); 
		Messages.clientMessages[38] = Messages.messages["Client_onUpdateData_xyz_p"];

		Messages.messages["Client_onUpdateData_xyz_r"] = new Message_Client_onUpdateData_xyz_r(39, "Client_onUpdateData_xyz_r", -1, -1, []); 
		Messages.clientMessages[39] = Messages.messages["Client_onUpdateData_xyz_r"];

		Messages.messages["Client_onUpdateData_ypr_optimized"] = new Message_Client_onUpdateData_ypr_optimized(40, "Client_onUpdateData_ypr_optimized", -1, -1, []); 
		Messages.clientMessages[40] = Messages.messages["Client_onUpdateData_ypr_optimized"];

		Messages.messages["Client_onUpdateData_yp_optimized"] = new Message_Client_onUpdateData_yp_optimized(41, "Client_onUpdateData_yp_optimized", -1, -1, []); 
		Messages.clientMessages[41] = Messages.messages["Client_onUpdateData_yp_optimized"];

		Messages.messages["Client_onUpdateData_yr_optimized"] = new Message_Client_onUpdateData_yr_optimized(42, "Client_onUpdateData_yr_optimized", -1, -1, []); 
		Messages.clientMessages[42] = Messages.messages["Client_onUpdateData_yr_optimized"];

		Messages.messages["Client_onUpdateData_pr_optimized"] = new Message_Client_onUpdateData_pr_optimized(43, "Client_onUpdateData_pr_optimized", -1, -1, []); 
		Messages.clientMessages[43] = Messages.messages["Client_onUpdateData_pr_optimized"];

		Messages.messages["Client_onUpdateData_y_optimized"] = new Message_Client_onUpdateData_y_optimized(44, "Client_onUpdateData_y_optimized", -1, -1, []); 
		Messages.clientMessages[44] = Messages.messages["Client_onUpdateData_y_optimized"];

		Messages.messages["Client_onUpdateData_p_optimized"] = new Message_Client_onUpdateData_p_optimized(45, "Client_onUpdateData_p_optimized", -1, -1, []); 
		Messages.clientMessages[45] = Messages.messages["Client_onUpdateData_p_optimized"];

		Messages.messages["Client_onUpdateData_r_optimized"] = new Message_Client_onUpdateData_r_optimized(46, "Client_onUpdateData_r_optimized", -1, -1, []); 
		Messages.clientMessages[46] = Messages.messages["Client_onUpdateData_r_optimized"];

		Messages.messages["Client_onUpdateData_xz_optimized"] = new Message_Client_onUpdateData_xz_optimized(47, "Client_onUpdateData_xz_optimized", -1, -1, []); 
		Messages.clientMessages[47] = Messages.messages["Client_onUpdateData_xz_optimized"];

		Messages.messages["Client_onUpdateData_xz_ypr_optimized"] = new Message_Client_onUpdateData_xz_ypr_optimized(48, "Client_onUpdateData_xz_ypr_optimized", -1, -1, []); 
		Messages.clientMessages[48] = Messages.messages["Client_onUpdateData_xz_ypr_optimized"];

		Messages.messages["Client_onUpdateData_xz_yp_optimized"] = new Message_Client_onUpdateData_xz_yp_optimized(49, "Client_onUpdateData_xz_yp_optimized", -1, -1, []); 
		Messages.clientMessages[49] = Messages.messages["Client_onUpdateData_xz_yp_optimized"];

		Messages.messages["Client_onUpdateData_xz_yr_optimized"] = new Message_Client_onUpdateData_xz_yr_optimized(50, "Client_onUpdateData_xz_yr_optimized", -1, -1, []); 
		Messages.clientMessages[50] = Messages.messages["Client_onUpdateData_xz_yr_optimized"];

		Messages.messages["Client_onUpdateData_xz_pr_optimized"] = new Message_Client_onUpdateData_xz_pr_optimized(51, "Client_onUpdateData_xz_pr_optimized", -1, -1, []); 
		Messages.clientMessages[51] = Messages.messages["Client_onUpdateData_xz_pr_optimized"];

		Messages.messages["Client_onUpdateData_xz_y_optimized"] = new Message_Client_onUpdateData_xz_y_optimized(52, "Client_onUpdateData_xz_y_optimized", -1, -1, []); 
		Messages.clientMessages[52] = Messages.messages["Client_onUpdateData_xz_y_optimized"];

		Messages.messages["Client_onUpdateData_xz_p_optimized"] = new Message_Client_onUpdateData_xz_p_optimized(53, "Client_onUpdateData_xz_p_optimized", -1, -1, []); 
		Messages.clientMessages[53] = Messages.messages["Client_onUpdateData_xz_p_optimized"];

		Messages.messages["Client_onUpdateData_xz_r_optimized"] = new Message_Client_onUpdateData_xz_r_optimized(54, "Client_onUpdateData_xz_r_optimized", -1, -1, []); 
		Messages.clientMessages[54] = Messages.messages["Client_onUpdateData_xz_r_optimized"];

		Messages.messages["Client_onUpdateData_xyz_optimized"] = new Message_Client_onUpdateData_xyz_optimized(55, "Client_onUpdateData_xyz_optimized", -1, -1, []); 
		Messages.clientMessages[55] = Messages.messages["Client_onUpdateData_xyz_optimized"];

		Messages.messages["Client_onUpdateData_xyz_ypr_optimized"] = new Message_Client_onUpdateData_xyz_ypr_optimized(56, "Client_onUpdateData_xyz_ypr_optimized", -1, -1, []); 
		Messages.clientMessages[56] = Messages.messages["Client_onUpdateData_xyz_ypr_optimized"];

		Messages.messages["Client_onUpdateData_xyz_yp_optimized"] = new Message_Client_onUpdateData_xyz_yp_optimized(57, "Client_onUpdateData_xyz_yp_optimized", -1, -1, []); 
		Messages.clientMessages[57] = Messages.messages["Client_onUpdateData_xyz_yp_optimized"];

		Messages.messages["Client_onUpdateData_xyz_yr_optimized"] = new Message_Client_onUpdateData_xyz_yr_optimized(58, "Client_onUpdateData_xyz_yr_optimized", -1, -1, []); 
		Messages.clientMessages[58] = Messages.messages["Client_onUpdateData_xyz_yr_optimized"];

		Messages.messages["Client_onUpdateData_xyz_pr_optimized"] = new Message_Client_onUpdateData_xyz_pr_optimized(59, "Client_onUpdateData_xyz_pr_optimized", -1, -1, []); 
		Messages.clientMessages[59] = Messages.messages["Client_onUpdateData_xyz_pr_optimized"];

		Messages.messages["Client_onUpdateData_xyz_y_optimized"] = new Message_Client_onUpdateData_xyz_y_optimized(60, "Client_onUpdateData_xyz_y_optimized", -1, -1, []); 
		Messages.clientMessages[60] = Messages.messages["Client_onUpdateData_xyz_y_optimized"];

		Messages.messages["Client_onUpdateData_xyz_p_optimized"] = new Message_Client_onUpdateData_xyz_p_optimized(61, "Client_onUpdateData_xyz_p_optimized", -1, -1, []); 
		Messages.clientMessages[61] = Messages.messages["Client_onUpdateData_xyz_p_optimized"];

		Messages.messages["Client_onUpdateData_xyz_r_optimized"] = new Message_Client_onUpdateData_xyz_r_optimized(62, "Client_onUpdateData_xyz_r_optimized", -1, -1, []); 
		Messages.clientMessages[62] = Messages.messages["Client_onUpdateData_xyz_r_optimized"];

		Messages.messages["Client_onImportServerErrorsDescr"] = new Message_Client_onImportServerErrorsDescr(63, "Client_onImportServerErrorsDescr", -1, -1, []); 
		Messages.clientMessages[63] = Messages.messages["Client_onImportServerErrorsDescr"];

		Messages.messages["Client_onImportClientSDK"] = new Message_Client_onImportClientSDK(64, "Client_onImportClientSDK", -1, -1, []); 
		Messages.clientMessages[64] = Messages.messages["Client_onImportClientSDK"];

		Messages.messages["Client_initSpaceData"] = new Message_Client_initSpaceData(65, "Client_initSpaceData", -1, -1, []); 
		Messages.clientMessages[65] = Messages.messages["Client_initSpaceData"];


		let Client_setSpaceData_argstypes: number[] = [];
		Client_setSpaceData_argstypes.push(4);
		Client_setSpaceData_argstypes.push(1);
		Client_setSpaceData_argstypes.push(1);
		Messages.messages["Client_setSpaceData"] = new Message_Client_setSpaceData(66, "Client_setSpaceData", -1, 0, Client_setSpaceData_argstypes);
		Messages.clientMessages[66] = Messages.messages["Client_setSpaceData"];


		let Client_delSpaceData_argstypes: number[] = [];
		Client_delSpaceData_argstypes.push(4);
		Client_delSpaceData_argstypes.push(1);
		Messages.messages["Client_delSpaceData"] = new Message_Client_delSpaceData(67, "Client_delSpaceData", -1, 0, Client_delSpaceData_argstypes);
		Messages.clientMessages[67] = Messages.messages["Client_delSpaceData"];


		let Client_onReqAccountResetPasswordCB_argstypes: number[] = [];
		Client_onReqAccountResetPasswordCB_argstypes.push(3);
		Messages.messages["Client_onReqAccountResetPasswordCB"] = new Message_Client_onReqAccountResetPasswordCB(68, "Client_onReqAccountResetPasswordCB", 2, 0, Client_onReqAccountResetPasswordCB_argstypes);
		Messages.clientMessages[68] = Messages.messages["Client_onReqAccountResetPasswordCB"];


		let Client_onReqAccountBindEmailCB_argstypes: number[] = [];
		Client_onReqAccountBindEmailCB_argstypes.push(3);
		Messages.messages["Client_onReqAccountBindEmailCB"] = new Message_Client_onReqAccountBindEmailCB(69, "Client_onReqAccountBindEmailCB", 2, 0, Client_onReqAccountBindEmailCB_argstypes);
		Messages.clientMessages[69] = Messages.messages["Client_onReqAccountBindEmailCB"];


		let Client_onReqAccountNewPasswordCB_argstypes: number[] = [];
		Client_onReqAccountNewPasswordCB_argstypes.push(3);
		Messages.messages["Client_onReqAccountNewPasswordCB"] = new Message_Client_onReqAccountNewPasswordCB(70, "Client_onReqAccountNewPasswordCB", 2, 0, Client_onReqAccountNewPasswordCB_argstypes);
		Messages.clientMessages[70] = Messages.messages["Client_onReqAccountNewPasswordCB"];

		Messages.messages["Client_onReloginBaseappSuccessfully"] = new Message_Client_onReloginBaseappSuccessfully(71, "Client_onReloginBaseappSuccessfully", -1, -1, []); 
		Messages.clientMessages[71] = Messages.messages["Client_onReloginBaseappSuccessfully"];

		Messages.messages["Client_onAppActiveTickCB"] = new Message_Client_onAppActiveTickCB(72, "Client_onAppActiveTickCB", 0, 0, []); 
		Messages.clientMessages[72] = Messages.messages["Client_onAppActiveTickCB"];

		Messages.messages["Client_onCreateAccountResult"] = new Message_Client_onCreateAccountResult(501, "Client_onCreateAccountResult", -1, -1, []); 
		Messages.clientMessages[501] = Messages.messages["Client_onCreateAccountResult"];

		Messages.messages["Client_onLoginSuccessfully"] = new Message_Client_onLoginSuccessfully(502, "Client_onLoginSuccessfully", -1, -1, []); 
		Messages.clientMessages[502] = Messages.messages["Client_onLoginSuccessfully"];

		Messages.messages["Client_onLoginFailed"] = new Message_Client_onLoginFailed(503, "Client_onLoginFailed", -1, -1, []); 
		Messages.clientMessages[503] = Messages.messages["Client_onLoginFailed"];


		let Client_onCreatedProxies_argstypes: number[] = [];
		Client_onCreatedProxies_argstypes.push(5);
		Client_onCreatedProxies_argstypes.push(8);
		Client_onCreatedProxies_argstypes.push(1);
		Messages.messages["Client_onCreatedProxies"] = new Message_Client_onCreatedProxies(504, "Client_onCreatedProxies", -1, 0, Client_onCreatedProxies_argstypes);
		Messages.clientMessages[504] = Messages.messages["Client_onCreatedProxies"];


		let Client_onLoginBaseappFailed_argstypes: number[] = [];
		Client_onLoginBaseappFailed_argstypes.push(3);
		Messages.messages["Client_onLoginBaseappFailed"] = new Message_Client_onLoginBaseappFailed(505, "Client_onLoginBaseappFailed", 2, 0, Client_onLoginBaseappFailed_argstypes);
		Messages.clientMessages[505] = Messages.messages["Client_onLoginBaseappFailed"];

		Messages.messages["Client_onRemoteMethodCall"] = new Message_Client_onRemoteMethodCall(506, "Client_onRemoteMethodCall", -1, -1, []); 
		Messages.clientMessages[506] = Messages.messages["Client_onRemoteMethodCall"];

		Messages.messages["Client_onEntityEnterWorld"] = new Message_Client_onEntityEnterWorld(507, "Client_onEntityEnterWorld", -1, -1, []); 
		Messages.clientMessages[507] = Messages.messages["Client_onEntityEnterWorld"];


		let Client_onEntityLeaveWorld_argstypes: number[] = [];
		Client_onEntityLeaveWorld_argstypes.push(8);
		Messages.messages["Client_onEntityLeaveWorld"] = new Message_Client_onEntityLeaveWorld(508, "Client_onEntityLeaveWorld", 4, 0, Client_onEntityLeaveWorld_argstypes);
		Messages.clientMessages[508] = Messages.messages["Client_onEntityLeaveWorld"];

		Messages.messages["Client_onEntityEnterSpace"] = new Message_Client_onEntityEnterSpace(509, "Client_onEntityEnterSpace", -1, -1, []); 
		Messages.clientMessages[509] = Messages.messages["Client_onEntityEnterSpace"];


		let Client_onEntityLeaveSpace_argstypes: number[] = [];
		Client_onEntityLeaveSpace_argstypes.push(8);
		Messages.messages["Client_onEntityLeaveSpace"] = new Message_Client_onEntityLeaveSpace(510, "Client_onEntityLeaveSpace", 4, 0, Client_onEntityLeaveSpace_argstypes);
		Messages.clientMessages[510] = Messages.messages["Client_onEntityLeaveSpace"];

		Messages.messages["Client_onUpdatePropertys"] = new Message_Client_onUpdatePropertys(511, "Client_onUpdatePropertys", -1, -1, []); 
		Messages.clientMessages[511] = Messages.messages["Client_onUpdatePropertys"];


		let Client_onEntityDestroyed_argstypes: number[] = [];
		Client_onEntityDestroyed_argstypes.push(8);
		Messages.messages["Client_onEntityDestroyed"] = new Message_Client_onEntityDestroyed(512, "Client_onEntityDestroyed", 4, 0, Client_onEntityDestroyed_argstypes);
		Messages.clientMessages[512] = Messages.messages["Client_onEntityDestroyed"];


		let Client_onStreamDataStarted_argstypes: number[] = [];
		Client_onStreamDataStarted_argstypes.push(7);
		Client_onStreamDataStarted_argstypes.push(4);
		Client_onStreamDataStarted_argstypes.push(1);
		Messages.messages["Client_onStreamDataStarted"] = new Message_Client_onStreamDataStarted(514, "Client_onStreamDataStarted", -1, 0, Client_onStreamDataStarted_argstypes);
		Messages.clientMessages[514] = Messages.messages["Client_onStreamDataStarted"];

		Messages.messages["Client_onStreamDataRecv"] = new Message_Client_onStreamDataRecv(515, "Client_onStreamDataRecv", -1, -1, []); 
		Messages.clientMessages[515] = Messages.messages["Client_onStreamDataRecv"];


		let Client_onStreamDataCompleted_argstypes: number[] = [];
		Client_onStreamDataCompleted_argstypes.push(7);
		Messages.messages["Client_onStreamDataCompleted"] = new Message_Client_onStreamDataCompleted(516, "Client_onStreamDataCompleted", 2, 0, Client_onStreamDataCompleted_argstypes);
		Messages.clientMessages[516] = Messages.messages["Client_onStreamDataCompleted"];


		let Client_onKicked_argstypes: number[] = [];
		Client_onKicked_argstypes.push(3);
		Messages.messages["Client_onKicked"] = new Message_Client_onKicked(517, "Client_onKicked", 2, 0, Client_onKicked_argstypes);
		Messages.clientMessages[517] = Messages.messages["Client_onKicked"];

		Messages.messages["Client_onImportClientMessages"] = new Message_Client_onImportClientMessages(518, "Client_onImportClientMessages", -1, -1, []); 
		Messages.clientMessages[518] = Messages.messages["Client_onImportClientMessages"];

		Messages.messages["Client_onImportClientEntityDef"] = new Message_Client_onImportClientEntityDef(519, "Client_onImportClientEntityDef", -1, -1, []); 
		Messages.clientMessages[519] = Messages.messages["Client_onImportClientEntityDef"];

		Messages.messages["Client_onHelloCB"] = new Message_Client_onHelloCB(521, "Client_onHelloCB", -1, -1, []); 
		Messages.clientMessages[521] = Messages.messages["Client_onHelloCB"];

		Messages.messages["Client_onScriptVersionNotMatch"] = new Message_Client_onScriptVersionNotMatch(522, "Client_onScriptVersionNotMatch", -1, -1, []); 
		Messages.clientMessages[522] = Messages.messages["Client_onScriptVersionNotMatch"];

		Messages.messages["Client_onVersionNotMatch"] = new Message_Client_onVersionNotMatch(523, "Client_onVersionNotMatch", -1, -1, []); 
		Messages.clientMessages[523] = Messages.messages["Client_onVersionNotMatch"];


		let Client_onControlEntity_argstypes: number[] = [];
		Client_onControlEntity_argstypes.push(8);
		Client_onControlEntity_argstypes.push(6);
		Messages.messages["Client_onControlEntity"] = new Message_Client_onControlEntity(524, "Client_onControlEntity", 5, 0, Client_onControlEntity_argstypes);
		Messages.clientMessages[524] = Messages.messages["Client_onControlEntity"];

		Messages.messages["Loginapp_reqCreateAccount"] = new Message_Loginapp_reqCreateAccount(2, "Loginapp_reqCreateAccount", -1, 0, []); 
		Messages.loginappMessages[2] = Messages.messages["Loginapp_reqCreateAccount"];

		Messages.messages["Loginapp_login"] = new Message_Loginapp_login(3, "Loginapp_login", -1, 0, []); 
		Messages.loginappMessages[3] = Messages.messages["Loginapp_login"];

		Messages.messages["Loginapp_hello"] = new Message_Loginapp_hello(4, "Loginapp_hello", -1, 0, []); 
		Messages.loginappMessages[4] = Messages.messages["Loginapp_hello"];

		Messages.messages["Loginapp_importClientMessages"] = new Message_Loginapp_importClientMessages(5, "Loginapp_importClientMessages", 0, 0, []); 
		Messages.loginappMessages[5] = Messages.messages["Loginapp_importClientMessages"];

		Messages.messages["Loginapp_reqCreateMailAccount"] = new Message_Loginapp_reqCreateMailAccount(6, "Loginapp_reqCreateMailAccount", -1, 0, []); 
		Messages.loginappMessages[6] = Messages.messages["Loginapp_reqCreateMailAccount"];

		Messages.messages["Loginapp_importClientSDK"] = new Message_Loginapp_importClientSDK(7, "Loginapp_importClientSDK", -1, 0, []); 
		Messages.loginappMessages[7] = Messages.messages["Loginapp_importClientSDK"];

		Messages.messages["Loginapp_importServerErrorsDescr"] = new Message_Loginapp_importServerErrorsDescr(8, "Loginapp_importServerErrorsDescr", 0, 0, []); 
		Messages.loginappMessages[8] = Messages.messages["Loginapp_importServerErrorsDescr"];

		Messages.messages["Loginapp_onClientActiveTick"] = new Message_Loginapp_onClientActiveTick(11, "Loginapp_onClientActiveTick", 0, 0, []); 
		Messages.loginappMessages[11] = Messages.messages["Loginapp_onClientActiveTick"];


		let Loginapp_reqAccountResetPassword_argstypes: number[] = [];
		Loginapp_reqAccountResetPassword_argstypes.push(1);
		Messages.messages["Loginapp_reqAccountResetPassword"] = new Message_Loginapp_reqAccountResetPassword(12, "Loginapp_reqAccountResetPassword", -1, 0, Loginapp_reqAccountResetPassword_argstypes);
		Messages.loginappMessages[12] = Messages.messages["Loginapp_reqAccountResetPassword"];


		let Baseapp_logoutBaseapp_argstypes: number[] = [];
		Baseapp_logoutBaseapp_argstypes.push(5);
		Baseapp_logoutBaseapp_argstypes.push(8);
		Messages.messages["Baseapp_logoutBaseapp"] = new Message_Baseapp_logoutBaseapp(24, "Baseapp_logoutBaseapp", 12, 0, Baseapp_logoutBaseapp_argstypes);
		Messages.baseappMessages[24] = Messages.messages["Baseapp_logoutBaseapp"];

		Messages.messages["Baseapp_onUpdateDataFromClient"] = new Message_Baseapp_onUpdateDataFromClient(27, "Baseapp_onUpdateDataFromClient", -1, -1, []); 
		Messages.baseappMessages[27] = Messages.messages["Baseapp_onUpdateDataFromClient"];

		Messages.messages["Baseapp_onUpdateDataFromClientForControlledEntity"] = new Message_Baseapp_onUpdateDataFromClientForControlledEntity(28, "Baseapp_onUpdateDataFromClientForControlledEntity", -1, -1, []); 
		Messages.baseappMessages[28] = Messages.messages["Baseapp_onUpdateDataFromClientForControlledEntity"];


		let Baseapp_reqAccountBindEmail_argstypes: number[] = [];
		Baseapp_reqAccountBindEmail_argstypes.push(8);
		Baseapp_reqAccountBindEmail_argstypes.push(1);
		Baseapp_reqAccountBindEmail_argstypes.push(1);
		Messages.messages["Baseapp_reqAccountBindEmail"] = new Message_Baseapp_reqAccountBindEmail(51, "Baseapp_reqAccountBindEmail", -1, 0, Baseapp_reqAccountBindEmail_argstypes);
		Messages.baseappMessages[51] = Messages.messages["Baseapp_reqAccountBindEmail"];


		let Baseapp_reqAccountNewPassword_argstypes: number[] = [];
		Baseapp_reqAccountNewPassword_argstypes.push(8);
		Baseapp_reqAccountNewPassword_argstypes.push(1);
		Baseapp_reqAccountNewPassword_argstypes.push(1);
		Messages.messages["Baseapp_reqAccountNewPassword"] = new Message_Baseapp_reqAccountNewPassword(54, "Baseapp_reqAccountNewPassword", -1, 0, Baseapp_reqAccountNewPassword_argstypes);
		Messages.baseappMessages[54] = Messages.messages["Baseapp_reqAccountNewPassword"];

		Messages.messages["Entity_forwardEntityMessageToCellappFromClient"] = new Message_Entity_forwardEntityMessageToCellappFromClient(58, "Entity_forwardEntityMessageToCellappFromClient", -1, -1, []); 
		Messages.baseappMessages[58] = Messages.messages["Entity_forwardEntityMessageToCellappFromClient"];

		Messages.messages["Baseapp_hello"] = new Message_Baseapp_hello(200, "Baseapp_hello", -1, -1, []); 
		Messages.baseappMessages[200] = Messages.messages["Baseapp_hello"];


		let Baseapp_loginBaseapp_argstypes: number[] = [];
		Baseapp_loginBaseapp_argstypes.push(1);
		Baseapp_loginBaseapp_argstypes.push(1);
		Messages.messages["Baseapp_loginBaseapp"] = new Message_Baseapp_loginBaseapp(202, "Baseapp_loginBaseapp", -1, 0, Baseapp_loginBaseapp_argstypes);
		Messages.baseappMessages[202] = Messages.messages["Baseapp_loginBaseapp"];


		let Baseapp_reloginBaseapp_argstypes: number[] = [];
		Baseapp_reloginBaseapp_argstypes.push(1);
		Baseapp_reloginBaseapp_argstypes.push(1);
		Baseapp_reloginBaseapp_argstypes.push(5);
		Baseapp_reloginBaseapp_argstypes.push(8);
		Messages.messages["Baseapp_reloginBaseapp"] = new Message_Baseapp_reloginBaseapp(204, "Baseapp_reloginBaseapp", -1, 0, Baseapp_reloginBaseapp_argstypes);
		Messages.baseappMessages[204] = Messages.messages["Baseapp_reloginBaseapp"];

		Messages.messages["Baseapp_onRemoteCallCellMethodFromClient"] = new Message_Baseapp_onRemoteCallCellMethodFromClient(205, "Baseapp_onRemoteCallCellMethodFromClient", -1, -1, []); 
		Messages.baseappMessages[205] = Messages.messages["Baseapp_onRemoteCallCellMethodFromClient"];

		Messages.messages["Baseapp_onClientActiveTick"] = new Message_Baseapp_onClientActiveTick(206, "Baseapp_onClientActiveTick", 0, 0, []); 
		Messages.baseappMessages[206] = Messages.messages["Baseapp_onClientActiveTick"];

		Messages.messages["Baseapp_importClientMessages"] = new Message_Baseapp_importClientMessages(207, "Baseapp_importClientMessages", 0, 0, []); 
		Messages.baseappMessages[207] = Messages.messages["Baseapp_importClientMessages"];

		Messages.messages["Baseapp_importClientEntityDef"] = new Message_Baseapp_importClientEntityDef(208, "Baseapp_importClientEntityDef", 0, 0, []); 
		Messages.baseappMessages[208] = Messages.messages["Baseapp_importClientEntityDef"];

		Messages.messages["Entity_onRemoteMethodCall"] = new Message_Entity_onRemoteMethodCall(302, "Entity_onRemoteMethodCall", -1, -1, []); 
		Messages.baseappMessages[302] = Messages.messages["Entity_onRemoteMethodCall"];


		return true;
	}
}