# Generated by Django 5.2.7 on 2025-10-26 02:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KBEUserExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_username', models.CharField(blank=True, max_length=30, null=True, verbose_name='操作系统用户')),
                ('system_user_uid', models.CharField(blank=True, max_length=30, null=True, verbose_name='操作系统用户uid')),
                ('kbe_root', models.CharField(blank=True, max_length=256, null=True, verbose_name='KBE_ROOT')),
                ('kbe_res_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='KBE_RES_PATH')),
                ('kbe_bin_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='KBE_BIN_PATH')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
