# Generated by Django 5.2.7 on 2025-10-26 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '性能分析',
                'verbose_name_plural': '性能分析',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PythonConsole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Python控制台',
                'verbose_name_plural': 'Python控制台',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SpaceViewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'SpaceViewer',
                'verbose_name_plural': 'SpaceViewer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Watcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Watcher',
                'verbose_name_plural': 'Watcher',
                'managed': False,
            },
        ),
    ]
