# Generated by Django 5.2.7 on 2025-10-30 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '状态',
                'verbose_name_plural': '状态',
                'managed': False,
            },
        ),
    ]
