# Generated by Django 5.2.7 on 2025-10-26 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '实时日志',
                'verbose_name_plural': '实时日志',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServerMachines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '进程状态',
                'verbose_name_plural': '进程状态',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServerManage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '服务器管理',
                'verbose_name_plural': '服务器管理',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServerConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, default='', help_text='名称', max_length=128, unique=True, verbose_name='配置名')),
                ('sys_user', models.CharField(default='', help_text='系统账号', max_length=128, verbose_name='系统账号')),
                ('config', models.TextField(default='', help_text='配置(JSON)', max_length=32768, verbose_name='配置')),
            ],
            options={
                'verbose_name': '服务器运行配置',
                'verbose_name_plural': '服务器运行配置',
            },
        ),
    ]
